### ISSUE TITLE
EW11 missing IP address 

### ISSUE THREAD

**Issue by Richard7619** [Jumpy07/Solis---SolisCloud-and-Home-Assistant#2]
Hi,

Great Project.
I have the hardware installed and it appears to be working. 
However I’m having issues setting up the IP address. 
I can see EW11 as a Wi-Fi network so connect and go to 10.10.100.254
the status shows Wi-Fi disconnected and no IP address. 
The photos show the setting I’ve used. Are there any I need to change? 
Also how do I create a static IP address? 

Thanks Richard 
![88C28AF9-606F-4261-B267-29260CDFE432](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/assets/135166611/c6f47835-77cd-411b-9fbb-824fcae656d4)
![5DE70510-FDF1-4B00-B82D-F91E53D4DE73](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/assets/135166611/52b142e1-394a-4f3a-b141-8648e8bc5a7f)
![C2888146-52AA-4906-8859-69E577740354](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/assets/135166611/1540f1f8-b7d1-4258-afef-6705ee6bb8b8)
![7918464D-ADA1-494B-B08B-B4B72275D0B0](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/assets/135166611/cfacf777-6665-4224-9e6d-15d0d2e41b25)
![20CD5AEB-8B22-47D0-80FE-9980CF0EA552](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/assets/135166611/cd2c39af-fefc-43ab-92c7-4ba124fb2356)
![36F625FA-2FE5-4BEF-A463-42AB73BB40E1](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/assets/135166611/e445c16f-24b7-4ca4-8984-392fc9b6d151)
![C77547B3-5AEA-4EB7-8094-15227CD32CAE](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/assets/135166611/6fffb554-87ad-4f4a-acaf-27dba52a8386)
![31DA877F-3AE1-4D58-9242-350A7C2A0099](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/assets/135166611/554fc7a7-f4cd-4c89-9ba5-5aa5f703d588)

**Comment by Jumpy07** [comment]
Remember and hit submit when you change the settings.. (button at bottom)

 

Do a scan for wifi.. enter password for you SSID

 

I am using DHCP on my LAN… so ip below only used if it doesn’t find DHCP server..

 



 

 

 

From: Richard Heslop ***@***.***> 
Sent: Sunday, June 11, 2023 5:40 PM
To: Jumpy07/Solis---SolisCloud-and-Home-Assistant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Jumpy07/Solis---SolisCloud-and-Home-Assistant] EW11 missing IP address (Issue #2)

 

Hi,

Great Project.
I have the hardware installed and it appears to be working.
However I’m having issues setting up the IP address.
I can see EW11 as a Wi-Fi network so connect and go to 10.10.100.254
the status shows Wi-Fi disconnected and no IP address.
The photos show the setting I’ve used. Are there any I need to change?
Also how do I create a static IP address?

Thanks Richard
 <https://user-images.githubusercontent.com/135166611/244952393-c6f47835-77cd-411b-9fbb-824fcae656d4.jpeg> 
 <https://user-images.githubusercontent.com/135166611/244952411-52b142e1-394a-4f3a-b141-8648e8bc5a7f.jpeg> 
 <https://user-images.githubusercontent.com/135166611/244952427-1540f1f8-b7d1-4258-afef-6705ee6bb8b8.jpeg> 
 <https://user-images.githubusercontent.com/135166611/244952432-cfacf777-6665-4224-9e6d-15d0d2e41b25.jpeg> 
 <https://user-images.githubusercontent.com/135166611/244952442-cd2c39af-fefc-43ab-92c7-4ba124fb2356.jpeg> 
 <https://user-images.githubusercontent.com/135166611/244952457-e445c16f-24b7-4ca4-8984-392fc9b6d151.jpeg> 
 <https://user-images.githubusercontent.com/135166611/244952472-6fffb554-87ad-4f4a-acaf-27dba52a8386.jpeg> 
 <https://user-images.githubusercontent.com/135166611/244952480-554fc7a7-f4cd-4c89-9ba5-5aa5f703d588.jpeg>

**Comment by Richard7619** [comment]
Thanks, I had been hitting submit and just connected again and settings in photos have saved including Wi-Fi and password. From the photos any idea what setting might be wrong?

**Comment by Jumpy07** [comment]
Not really.. do you have DHCP turned off ?

**Comment by Richard7619** [comment]
No DHCP is on.

**Comment by ciaranmcgirl** [comment]
- Disable dhcp under "wan settings" (this will allow you to set a static wireless address)
- set your static wan ip, subnet mask, gateway and dns under wan settings (this should be on whatever subnet your router works with, I set mine to 192.168.1.200, netmask 255.255.255.0, gateway 192.168.1.1, dns 192.168.1.1  but obviously check your router isn't already using the one you set!) 

Hit submit and then restart the device 

It should disconnect and then (provided you added the correct wifi SSID and password) connect to your home network.

you can now connect to your home network and connect to the web interface via 192.168.1.200.

HTH

**Comment by Richard7619** [comment]
OK, So I think I have this part sorted. 
I'll explain in case other Newbies find it helpful. 
I was expecting the router devices to have a name like EW11 or Elfin but it's actually called lwip0.
That is connected so I can get it's IP as 192.168.1.218. This was my missing link. 
Then the settings page use that for the WAN IP, then 255.255.255.0 and the router IP for the gateway.
The Lan IP is the 10.10.100.254 which is the AP you use for setting it initially. 
The settings show it's wi-fi is connected and I'm showing some sent and received frames. 
I'm still having issues with the Solax integration but I'll ask separately on that related project. 
Thanks,
