### ISSUE TITLE
Wiring diagram - 485A1/B1 + 485A2/B2 the wrong way round?

### ISSUE THREAD

**Issue by nutkracker** [Jumpy07/Solis---SolisCloud-and-Home-Assistant#5]
Hi, thanks for putting this together...  I've now got the components but querying the wiring of the modbus.

I think I've spotted an issue with the wiring diagram on https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant#connecting-it-all-up.  If you compare the GC-1201 RS485 ModBus photo vs the wiring diagram, the 485A1/B1 and 485A2/B2 are the wrong way round on the wiring diagram.

I checked the photo of your actual build and yes it looks like the wires from the Elfin EW11 go to 485A2 and 485B2.

Am I correct...  or does it actually matter?

@Jumpy07 

Thank you!
Nutz

**Comment by Jumpy07** [comment]
A-A
B-B
