### ISSUE TITLE
Static IP?

### ISSUE THREAD

**Issue by FarmingMartin** [Jumpy07/Solis---SolisCloud-and-Home-Assistant#6]
Hi you mentioned in your description that it need a static ip. 
Can anyone confirm if it my router that needs the static IP or is it within the settings of the Elfin-EW11?
The reason I am asking is because when I just googled how to change my router to Static IP it said like most home internet routers you can't change it to static IP unless you get a business account.

**Comment by Jumpy07** [comment]
Just static on the Elfin..

**Comment by FarmingMartin** [comment]
Thanks just regoogled it and realised you had to set it up on individual devises, just logged onto my router settings and found it. Thanks
