### ISSUE TITLE
Link of manual is dead.

### ISSUE THREAD

**Issue by chronvas** [Jumpy07/Solis---SolisCloud-and-Home-Assistant#8]
The link of the manual is dead.
Scanning the QR code of my device (GC-1201S not 1201K as the manual suggests) returns this url: http://qr61.cn/oadszU/qqpQvlf 
Eventually resolves into this pdf: 
[GC-1201S二主一从缓存型RS-485集线器(HUB)说明书V1.1.pdf](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/files/14029263/GC-1201S.RS-485.HUB.V1.1.pdf)

If anyone can translate this that would be great.

**Comment by Jumpy07** [comment]
Use google to translate

**Comment by chronvas** [comment]
> Use google to translate

Still link of manual is dead.
PDF also does not allow copy otherwise I would have used Google don't you think?
Although closing issues with such a dismissive manner.. something I definitely wouldn't do
